// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/panther-labs/panther/api/gateway/analysis/models"
)

// NewCreateDataModelParams creates a new CreateDataModelParams object
// with the default values initialized.
func NewCreateDataModelParams() *CreateDataModelParams {
	var ()
	return &CreateDataModelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDataModelParamsWithTimeout creates a new CreateDataModelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDataModelParamsWithTimeout(timeout time.Duration) *CreateDataModelParams {
	var ()
	return &CreateDataModelParams{

		timeout: timeout,
	}
}

// NewCreateDataModelParamsWithContext creates a new CreateDataModelParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDataModelParamsWithContext(ctx context.Context) *CreateDataModelParams {
	var ()
	return &CreateDataModelParams{

		Context: ctx,
	}
}

// NewCreateDataModelParamsWithHTTPClient creates a new CreateDataModelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDataModelParamsWithHTTPClient(client *http.Client) *CreateDataModelParams {
	var ()
	return &CreateDataModelParams{
		HTTPClient: client,
	}
}

/*CreateDataModelParams contains all the parameters to send to the API endpoint
for the create data model operation typically these are written to a http.Request
*/
type CreateDataModelParams struct {

	/*Body*/
	Body *models.UpdateDataModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create data model params
func (o *CreateDataModelParams) WithTimeout(timeout time.Duration) *CreateDataModelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create data model params
func (o *CreateDataModelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create data model params
func (o *CreateDataModelParams) WithContext(ctx context.Context) *CreateDataModelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create data model params
func (o *CreateDataModelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create data model params
func (o *CreateDataModelParams) WithHTTPClient(client *http.Client) *CreateDataModelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create data model params
func (o *CreateDataModelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create data model params
func (o *CreateDataModelParams) WithBody(body *models.UpdateDataModel) *CreateDataModelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create data model params
func (o *CreateDataModelParams) SetBody(body *models.UpdateDataModel) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDataModelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
