// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGlobalParams creates a new GetGlobalParams object
// with the default values initialized.
func NewGetGlobalParams() *GetGlobalParams {
	var ()
	return &GetGlobalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGlobalParamsWithTimeout creates a new GetGlobalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGlobalParamsWithTimeout(timeout time.Duration) *GetGlobalParams {
	var ()
	return &GetGlobalParams{

		timeout: timeout,
	}
}

// NewGetGlobalParamsWithContext creates a new GetGlobalParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGlobalParamsWithContext(ctx context.Context) *GetGlobalParams {
	var ()
	return &GetGlobalParams{

		Context: ctx,
	}
}

// NewGetGlobalParamsWithHTTPClient creates a new GetGlobalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGlobalParamsWithHTTPClient(client *http.Client) *GetGlobalParams {
	var ()
	return &GetGlobalParams{
		HTTPClient: client,
	}
}

/*GetGlobalParams contains all the parameters to send to the API endpoint
for the get global operation typically these are written to a http.Request
*/
type GetGlobalParams struct {

	/*GlobalID
	  Unique ASCII global identifier

	*/
	GlobalID string
	/*VersionID
	  The version of the analysis to retrieve

	*/
	VersionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get global params
func (o *GetGlobalParams) WithTimeout(timeout time.Duration) *GetGlobalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get global params
func (o *GetGlobalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get global params
func (o *GetGlobalParams) WithContext(ctx context.Context) *GetGlobalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get global params
func (o *GetGlobalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get global params
func (o *GetGlobalParams) WithHTTPClient(client *http.Client) *GetGlobalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get global params
func (o *GetGlobalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGlobalID adds the globalID to the get global params
func (o *GetGlobalParams) WithGlobalID(globalID string) *GetGlobalParams {
	o.SetGlobalID(globalID)
	return o
}

// SetGlobalID adds the globalId to the get global params
func (o *GetGlobalParams) SetGlobalID(globalID string) {
	o.GlobalID = globalID
}

// WithVersionID adds the versionID to the get global params
func (o *GetGlobalParams) WithVersionID(versionID *string) *GetGlobalParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get global params
func (o *GetGlobalParams) SetVersionID(versionID *string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGlobalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param globalId
	qrGlobalID := o.GlobalID
	qGlobalID := qrGlobalID
	if qGlobalID != "" {
		if err := r.SetQueryParam("globalId", qGlobalID); err != nil {
			return err
		}
	}

	if o.VersionID != nil {

		// query param versionId
		var qrVersionID string
		if o.VersionID != nil {
			qrVersionID = *o.VersionID
		}
		qVersionID := qrVersionID
		if qVersionID != "" {
			if err := r.SetQueryParam("versionId", qVersionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
