// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDataModelParams creates a new GetDataModelParams object
// with the default values initialized.
func NewGetDataModelParams() *GetDataModelParams {
	var ()
	return &GetDataModelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataModelParamsWithTimeout creates a new GetDataModelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDataModelParamsWithTimeout(timeout time.Duration) *GetDataModelParams {
	var ()
	return &GetDataModelParams{

		timeout: timeout,
	}
}

// NewGetDataModelParamsWithContext creates a new GetDataModelParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDataModelParamsWithContext(ctx context.Context) *GetDataModelParams {
	var ()
	return &GetDataModelParams{

		Context: ctx,
	}
}

// NewGetDataModelParamsWithHTTPClient creates a new GetDataModelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDataModelParamsWithHTTPClient(client *http.Client) *GetDataModelParams {
	var ()
	return &GetDataModelParams{
		HTTPClient: client,
	}
}

/*GetDataModelParams contains all the parameters to send to the API endpoint
for the get data model operation typically these are written to a http.Request
*/
type GetDataModelParams struct {

	/*DataModelID
	  Unique ASCII dataModel identifier

	*/
	DataModelID string
	/*VersionID
	  The version of the analysis to retrieve

	*/
	VersionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get data model params
func (o *GetDataModelParams) WithTimeout(timeout time.Duration) *GetDataModelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data model params
func (o *GetDataModelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data model params
func (o *GetDataModelParams) WithContext(ctx context.Context) *GetDataModelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data model params
func (o *GetDataModelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data model params
func (o *GetDataModelParams) WithHTTPClient(client *http.Client) *GetDataModelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data model params
func (o *GetDataModelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataModelID adds the dataModelID to the get data model params
func (o *GetDataModelParams) WithDataModelID(dataModelID string) *GetDataModelParams {
	o.SetDataModelID(dataModelID)
	return o
}

// SetDataModelID adds the dataModelId to the get data model params
func (o *GetDataModelParams) SetDataModelID(dataModelID string) {
	o.DataModelID = dataModelID
}

// WithVersionID adds the versionID to the get data model params
func (o *GetDataModelParams) WithVersionID(versionID *string) *GetDataModelParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get data model params
func (o *GetDataModelParams) SetVersionID(versionID *string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataModelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param dataModelId
	qrDataModelID := o.DataModelID
	qDataModelID := qrDataModelID
	if qDataModelID != "" {
		if err := r.SetQueryParam("dataModelId", qDataModelID); err != nil {
			return err
		}
	}

	if o.VersionID != nil {

		// query param versionId
		var qrVersionID string
		if o.VersionID != nil {
			qrVersionID = *o.VersionID
		}
		qVersionID := qrVersionID
		if qVersionID != "" {
			if err := r.SetQueryParam("versionId", qVersionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
