// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/panther-labs/panther/api/gateway/analysis/models"
)

// ListGlobalsReader is a Reader for the ListGlobals structure.
type ListGlobalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGlobalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListGlobalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListGlobalsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListGlobalsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListGlobalsOK creates a ListGlobalsOK with default headers values
func NewListGlobalsOK() *ListGlobalsOK {
	return &ListGlobalsOK{}
}

/*ListGlobalsOK handles this case with default header values.

OK
*/
type ListGlobalsOK struct {
	Payload *models.GlobalList
}

func (o *ListGlobalsOK) Error() string {
	return fmt.Sprintf("[GET /global/list][%d] listGlobalsOK  %+v", 200, o.Payload)
}

func (o *ListGlobalsOK) GetPayload() *models.GlobalList {
	return o.Payload
}

func (o *ListGlobalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GlobalList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGlobalsBadRequest creates a ListGlobalsBadRequest with default headers values
func NewListGlobalsBadRequest() *ListGlobalsBadRequest {
	return &ListGlobalsBadRequest{}
}

/*ListGlobalsBadRequest handles this case with default header values.

Bad request
*/
type ListGlobalsBadRequest struct {
	Payload *models.Error
}

func (o *ListGlobalsBadRequest) Error() string {
	return fmt.Sprintf("[GET /global/list][%d] listGlobalsBadRequest  %+v", 400, o.Payload)
}

func (o *ListGlobalsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListGlobalsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGlobalsInternalServerError creates a ListGlobalsInternalServerError with default headers values
func NewListGlobalsInternalServerError() *ListGlobalsInternalServerError {
	return &ListGlobalsInternalServerError{}
}

/*ListGlobalsInternalServerError handles this case with default header values.

Internal server error
*/
type ListGlobalsInternalServerError struct {
}

func (o *ListGlobalsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /global/list][%d] listGlobalsInternalServerError ", 500)
}

func (o *ListGlobalsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
