// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListGlobalsParams creates a new ListGlobalsParams object
// with the default values initialized.
func NewListGlobalsParams() *ListGlobalsParams {
	var (
		pageDefault     = int64(1)
		pageSizeDefault = int64(25)
		sortDirDefault  = string("ascending")
	)
	return &ListGlobalsParams{
		Page:     &pageDefault,
		PageSize: &pageSizeDefault,
		SortDir:  &sortDirDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListGlobalsParamsWithTimeout creates a new ListGlobalsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListGlobalsParamsWithTimeout(timeout time.Duration) *ListGlobalsParams {
	var (
		pageDefault     = int64(1)
		pageSizeDefault = int64(25)
		sortDirDefault  = string("ascending")
	)
	return &ListGlobalsParams{
		Page:     &pageDefault,
		PageSize: &pageSizeDefault,
		SortDir:  &sortDirDefault,

		timeout: timeout,
	}
}

// NewListGlobalsParamsWithContext creates a new ListGlobalsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListGlobalsParamsWithContext(ctx context.Context) *ListGlobalsParams {
	var (
		pageDefault     = int64(1)
		pageSizeDefault = int64(25)
		sortDirDefault  = string("ascending")
	)
	return &ListGlobalsParams{
		Page:     &pageDefault,
		PageSize: &pageSizeDefault,
		SortDir:  &sortDirDefault,

		Context: ctx,
	}
}

// NewListGlobalsParamsWithHTTPClient creates a new ListGlobalsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListGlobalsParamsWithHTTPClient(client *http.Client) *ListGlobalsParams {
	var (
		pageDefault     = int64(1)
		pageSizeDefault = int64(25)
		sortDirDefault  = string("ascending")
	)
	return &ListGlobalsParams{
		Page:       &pageDefault,
		PageSize:   &pageSizeDefault,
		SortDir:    &sortDirDefault,
		HTTPClient: client,
	}
}

/*ListGlobalsParams contains all the parameters to send to the API endpoint
for the list globals operation typically these are written to a http.Request
*/
type ListGlobalsParams struct {

	/*Page
	  Which page of results to retrieve

	*/
	Page *int64
	/*PageSize
	  Number of items in each page of results

	*/
	PageSize *int64
	/*SortDir
	  Sort direction

	*/
	SortDir *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list globals params
func (o *ListGlobalsParams) WithTimeout(timeout time.Duration) *ListGlobalsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list globals params
func (o *ListGlobalsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list globals params
func (o *ListGlobalsParams) WithContext(ctx context.Context) *ListGlobalsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list globals params
func (o *ListGlobalsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list globals params
func (o *ListGlobalsParams) WithHTTPClient(client *http.Client) *ListGlobalsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list globals params
func (o *ListGlobalsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list globals params
func (o *ListGlobalsParams) WithPage(page *int64) *ListGlobalsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list globals params
func (o *ListGlobalsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the list globals params
func (o *ListGlobalsParams) WithPageSize(pageSize *int64) *ListGlobalsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list globals params
func (o *ListGlobalsParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSortDir adds the sortDir to the list globals params
func (o *ListGlobalsParams) WithSortDir(sortDir *string) *ListGlobalsParams {
	o.SetSortDir(sortDir)
	return o
}

// SetSortDir adds the sortDir to the list globals params
func (o *ListGlobalsParams) SetSortDir(sortDir *string) {
	o.SortDir = sortDir
}

// WriteToRequest writes these params to a swagger request
func (o *ListGlobalsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.SortDir != nil {

		// query param sortDir
		var qrSortDir string
		if o.SortDir != nil {
			qrSortDir = *o.SortDir
		}
		qSortDir := qrSortDir
		if qSortDir != "" {
			if err := r.SetQueryParam("sortDir", qSortDir); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
