// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/panther-labs/panther/api/gateway/analysis/models"
)

// ListDataModelsReader is a Reader for the ListDataModels structure.
type ListDataModelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDataModelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDataModelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListDataModelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListDataModelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListDataModelsOK creates a ListDataModelsOK with default headers values
func NewListDataModelsOK() *ListDataModelsOK {
	return &ListDataModelsOK{}
}

/*ListDataModelsOK handles this case with default header values.

OK
*/
type ListDataModelsOK struct {
	Payload *models.DataModelList
}

func (o *ListDataModelsOK) Error() string {
	return fmt.Sprintf("[GET /datamodel/list][%d] listDataModelsOK  %+v", 200, o.Payload)
}

func (o *ListDataModelsOK) GetPayload() *models.DataModelList {
	return o.Payload
}

func (o *ListDataModelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataModelList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataModelsBadRequest creates a ListDataModelsBadRequest with default headers values
func NewListDataModelsBadRequest() *ListDataModelsBadRequest {
	return &ListDataModelsBadRequest{}
}

/*ListDataModelsBadRequest handles this case with default header values.

Bad request
*/
type ListDataModelsBadRequest struct {
	Payload *models.Error
}

func (o *ListDataModelsBadRequest) Error() string {
	return fmt.Sprintf("[GET /datamodel/list][%d] listDataModelsBadRequest  %+v", 400, o.Payload)
}

func (o *ListDataModelsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListDataModelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataModelsInternalServerError creates a ListDataModelsInternalServerError with default headers values
func NewListDataModelsInternalServerError() *ListDataModelsInternalServerError {
	return &ListDataModelsInternalServerError{}
}

/*ListDataModelsInternalServerError handles this case with default header values.

Internal server error
*/
type ListDataModelsInternalServerError struct {
}

func (o *ListDataModelsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /datamodel/list][%d] listDataModelsInternalServerError ", 500)
}

func (o *ListDataModelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
