// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/panther-labs/panther/api/gateway/analysis/models"
)

// NewModifyDataModelParams creates a new ModifyDataModelParams object
// with the default values initialized.
func NewModifyDataModelParams() *ModifyDataModelParams {
	var ()
	return &ModifyDataModelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyDataModelParamsWithTimeout creates a new ModifyDataModelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyDataModelParamsWithTimeout(timeout time.Duration) *ModifyDataModelParams {
	var ()
	return &ModifyDataModelParams{

		timeout: timeout,
	}
}

// NewModifyDataModelParamsWithContext creates a new ModifyDataModelParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifyDataModelParamsWithContext(ctx context.Context) *ModifyDataModelParams {
	var ()
	return &ModifyDataModelParams{

		Context: ctx,
	}
}

// NewModifyDataModelParamsWithHTTPClient creates a new ModifyDataModelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifyDataModelParamsWithHTTPClient(client *http.Client) *ModifyDataModelParams {
	var ()
	return &ModifyDataModelParams{
		HTTPClient: client,
	}
}

/*ModifyDataModelParams contains all the parameters to send to the API endpoint
for the modify data model operation typically these are written to a http.Request
*/
type ModifyDataModelParams struct {

	/*Body*/
	Body *models.UpdateDataModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify data model params
func (o *ModifyDataModelParams) WithTimeout(timeout time.Duration) *ModifyDataModelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify data model params
func (o *ModifyDataModelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify data model params
func (o *ModifyDataModelParams) WithContext(ctx context.Context) *ModifyDataModelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify data model params
func (o *ModifyDataModelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify data model params
func (o *ModifyDataModelParams) WithHTTPClient(client *http.Client) *ModifyDataModelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify data model params
func (o *ModifyDataModelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify data model params
func (o *ModifyDataModelParams) WithBody(body *models.UpdateDataModel) *ModifyDataModelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify data model params
func (o *ModifyDataModelParams) SetBody(body *models.UpdateDataModel) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyDataModelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
