// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Panther is a Cloud-Native SIEM for the Modern Security Team.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/panther-labs/panther/api/gateway/analysis/models"
)

// ModifyDataModelReader is a Reader for the ModifyDataModel structure.
type ModifyDataModelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyDataModelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyDataModelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewModifyDataModelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewModifyDataModelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewModifyDataModelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewModifyDataModelOK creates a ModifyDataModelOK with default headers values
func NewModifyDataModelOK() *ModifyDataModelOK {
	return &ModifyDataModelOK{}
}

/*ModifyDataModelOK handles this case with default header values.

OK
*/
type ModifyDataModelOK struct {
	Payload *models.DataModel
}

func (o *ModifyDataModelOK) Error() string {
	return fmt.Sprintf("[POST /datamodel/update][%d] modifyDataModelOK  %+v", 200, o.Payload)
}

func (o *ModifyDataModelOK) GetPayload() *models.DataModel {
	return o.Payload
}

func (o *ModifyDataModelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyDataModelBadRequest creates a ModifyDataModelBadRequest with default headers values
func NewModifyDataModelBadRequest() *ModifyDataModelBadRequest {
	return &ModifyDataModelBadRequest{}
}

/*ModifyDataModelBadRequest handles this case with default header values.

Bad request
*/
type ModifyDataModelBadRequest struct {
	Payload *models.Error
}

func (o *ModifyDataModelBadRequest) Error() string {
	return fmt.Sprintf("[POST /datamodel/update][%d] modifyDataModelBadRequest  %+v", 400, o.Payload)
}

func (o *ModifyDataModelBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ModifyDataModelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyDataModelNotFound creates a ModifyDataModelNotFound with default headers values
func NewModifyDataModelNotFound() *ModifyDataModelNotFound {
	return &ModifyDataModelNotFound{}
}

/*ModifyDataModelNotFound handles this case with default header values.

DataModel not found
*/
type ModifyDataModelNotFound struct {
}

func (o *ModifyDataModelNotFound) Error() string {
	return fmt.Sprintf("[POST /datamodel/update][%d] modifyDataModelNotFound ", 404)
}

func (o *ModifyDataModelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyDataModelInternalServerError creates a ModifyDataModelInternalServerError with default headers values
func NewModifyDataModelInternalServerError() *ModifyDataModelInternalServerError {
	return &ModifyDataModelInternalServerError{}
}

/*ModifyDataModelInternalServerError handles this case with default header values.

Internal server error
*/
type ModifyDataModelInternalServerError struct {
}

func (o *ModifyDataModelInternalServerError) Error() string {
	return fmt.Sprintf("[POST /datamodel/update][%d] modifyDataModelInternalServerError ", 500)
}

func (o *ModifyDataModelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
