# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Alert Outputs + Delivery

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues: [true, false]
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of base LayerVersion ARNs to attach to every Lambda function
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda and API Gateway
    AllowedValues: ['', Active, PassThrough]
    Default: ''

  AlertRetryDurationMins:
    Type: Number
    Description: Alerts which fail to send will be retried for this duration
    Default: 30
    MinValue: 5
    MaxValue: 10080 # 1 week
  MinRetryDelaySecs:
    Type: Number
    Description: Wait at least this long before retrying a failed alert
    Default: 30
    MinValue: 1
    MaxValue: 86400 # 1 day
  MaxRetryDelaySecs:
    Type: Number
    Description: Wait at most this long before retrying a failed alert
    Default: 300 # 5 mins
    MinValue: 1
    MaxValue: 86400 # 1 day
  AlertSqsRetentionSec:
    Type: Number
    Description: Number of seconds SQS will retain a message in the alerts queue
    Default: 259200 # 3 days
    MinValue: 60
    MaxValue: 1209600
  AppFqdn:
    Type: String
    Description: FQDN for the Panther web app (e.g. 1.2.3.4 or app.runpanther.io)
  SQSKeyId:
    Type: String
    Description: KMS key ID for SQS encryption

Conditions:
  AttachLayers: !Not [!Equals [!Join ['', !Ref LayerVersionArns], '']]
  TracingEnabled: !Not [!Equals ['', !Ref TracingMode]]

Resources:
  ##### Outputs API #####
  OutputsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: outputId
          AttributeType: S
        - AttributeName: displayName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: displayName-index
          KeySchema:
            - AttributeName: displayName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: outputId
          KeyType: HASH
      PointInTimeRecoverySpecification: # Create periodic table backups
        PointInTimeRecoveryEnabled: True
      SSESpecification: # Enable server-side encryption
        SSEEnabled: True
      TableName: panther-outputs

  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/panther-alert-outputs
      TargetKeyId: !Ref EncryptionKey

  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encrypts Panther's alert output configuration
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/core/outputs_api/main
      Description: CRUD actions for alert outputs
      Environment:
        Variables:
          DEBUG: !Ref Debug
          KEY_ID: !Ref EncryptionKey
          OUTPUTS_TABLE_NAME: !Ref OutputsTable
          OUTPUTS_DISPLAY_NAME_INDEX_NAME: displayName-index
      FunctionName: panther-outputs-api
      Handler: main
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      MemorySize: 512
      Runtime: go1.x
      Timeout: 60
      Tracing: !If [TracingEnabled, !Ref TracingMode, !Ref 'AWS::NoValue']
      Policies:
        - Id: OutputsTables
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt OutputsTable.Arn
                - !Sub '${OutputsTable.Arn}/index/*'
        - Id: CredentialEncryption
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
              Resource: !GetAtt EncryptionKey.Arn

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-outputs-api
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  ##### Alert Delivery #####
  AlertQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-alerts
      MessageRetentionPeriod: !Ref AlertSqsRetentionSec
      KmsMasterKeyId: !Ref SQSKeyId
      VisibilityTimeout: 60 # Should match lambda timeout

  AlertDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/core/alert_delivery/main
      Description: Dispatch alerts to their specified outputs
      Environment:
        Variables:
          ALERT_QUEUE_URL: !Ref AlertQueue
          ALERT_RETRY_DURATION_MINS: !Ref AlertRetryDurationMins
          ALERT_URL_PREFIX: !Sub https://${AppFqdn}/log-analysis/alerts/
          MAX_RETRY_DELAY_SECS: !Ref MaxRetryDelaySecs
          MIN_RETRY_DELAY_SECS: !Ref MinRetryDelaySecs
          OUTPUTS_API: panther-outputs-api
          OUTPUTS_REFRESH_INTERVAL_MIN: '5'
          POLICY_URL_PREFIX: !Sub https://${AppFqdn}/cloud-security/policies/
      Events:
        AlertQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt AlertQueue.Arn
            BatchSize: 10
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      FunctionName: panther-alert-delivery
      Handler: main
      MemorySize: 128
      Runtime: go1.x
      Timeout: 60
      Tracing: !If [TracingEnabled, !Ref TracingMode, !Ref 'AWS::NoValue']
      Policies:
        - Id: OutputsAPI
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:panther-outputs-api'
        - Id: PublishSnsMessage
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: '*'
        - Id: SendSqsAlert
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: '*'
        - Id: DecryptAlertMessages
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
        - Id: ReceiveAndDeleteAlerts
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt AlertQueue.Arn

  AlertDeliveryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-alert-delivery
      RetentionInDays: !Ref CloudWatchLogRetentionDays
